rest: true

http:
  port: 9925

  cors:
    enabled: true
    allowed_origins:
      - "http://localhost:8080"
      - "http://localhost:9926"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
    allow_credentials: true

graphqlSchema:
  files: 'schema.graphql'

jsResource:
  files: 'resources.js'

static:
  files: 'web/dist/**/*'
  urlPath: '/'
